name: Publish new version to PyPI

on: [push]

jobs:
  quality_cheks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.7, 3.8, 3.9, 3.10]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and the package
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run pytest
        run: pytest tests
